// solidColors.ts

interface SingleColor {
  name: string;
  hex: string;
}

export const SOLID_COLORS: SingleColor[] = [
  // Original colors
  { name: "Bottle", hex: "#174835" },
  { name: "Navy", hex: "#000080" },
  { name: "Royal", hex: "#4169E1" },
  { name: "Cardinal", hex: "#C41E3A" },
  { name: "Maroon", hex: "#800000" },
  { name: "Kelly", hex: "#4CBB17" },
  { name: "Forest", hex: "#228B22" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Purple", hex: "#800080" },
  { name: "Brown", hex: "#964B00" },
  { name: "Coffee", hex: "#ad672d" },
  { name: "Denim", hex: "#1f315c" },
  { name: "Raspberry", hex: "#87234b" },
  { name: "Army Brown", hex: "#756649" },
  { name: "Army Green", hex: "#273808" },
  { name: "Mustard", hex: "#E4B44C" },
  { name: "Coral Red", hex: "#e01969" },
  { name: "Coral Melange", hex: "#fc033d" },
  { name: "Bottle Melange", hex: "#024f30" },
  { name: "Oatmeal Melange", hex: "#848786" },
  { name: "Charcoal", hex: "#575656" },
  { name: "Charcoal Charcoal", hex: "#adb1ba" },
  { name: "Stone", hex: "#edda85" },
  { name: "Ruby Red", hex: "#c70230" },
  { name: "Graphite Grey", hex: "#373e4f" },
  { name: "Grey Melange", hex: "#adb1ba" },
  { name: "Dark Grey", hex: "#575d66" },
  { name: "Bark Brown", hex: "#242625" },
  { name: "Navy Melange", hex: "#222940" },
  { name: "Burgundy Melange", hex: "#61291c" },
  { name: "Charcoal Melange", hex: "#5e6063" },
  { name: "Royal Melange", hex: "#10316e" },
  { name: "Emerald", hex: "#21c46b" },
  { name: "Lilac", hex: "#e8b6f0" },
  { name: "Lemon", hex: "#ede18e" },
  { name: "Peach", hex: "#ffc59c" },
  { name: "Mint Green", hex: "#9ff5d1" },
  { name: "Slate Grey", hex: "#454a48" },
  { name: "Sky Blue", hex: "#9dd6f2" },
  { name: "Steel Grey", hex: "#5c554e" },
  { name: "Powder Blue", hex: "#3bd5f7" },
  { name: "Airforce Blue", hex: "#23799e" },
  { name: "Cyber Lime", hex: "#e4f73b" },
  { name: "Cyber Pink", hex: "#e00284" },
  { name: "Cyber Yellow", hex: "#d9f505" },
  { name: "Cyber Orange", hex: "#fc630a" },
  { name: "Red Melange", hex: "#c72842" },
  { name: "Pink Melange", hex: "#fa8cbf" },
  { name: "Military Melange", hex: "#525c4d" },
  { name: "Lumo Yellow", hex: "#e2f720" },
  { name: "Lumo Orange", hex: "#fc8403" },
  { name: "Dusty Pink", hex: "#BF8177" },
  { name: "Burnt Orange", hex: "#d1562a" },
  { name: "Khaki", hex: "#9e9365" },
  { name: "Dark Khaki", hex: "#917e67" },
  { name: "Sand", hex: "#cfb688" },
  { name: "Military Green", hex: "#3c4229" },
  { name: "Military Brown", hex: "#915e20" },
  { name: "Camel", hex: "#75655b" },
  { name: "Fuchsia", hex: "#e84869" },
  { name: "Athletic Gold", hex: "#FFB81C" },
  { name: "Vegas Gold", hex: "#C5B358" },
  { name: "Graphite", hex: "#383838" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Heather", hex: "#9CA5AE" },
  { name: "Oxford", hex: "#EFEFEF" },
  { name: "South Africa Green", hex: "#03731f" },

  // Adding missing basic colors
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Red", hex: "#FF0000" },
  { name: "Green", hex: "#008000" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Olive", hex: "#808000" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Grey", hex: "#808080" },
  { name: "Aqua", hex: "#00FFFF" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "Tan", hex: "#D2B48C" },
];
